version: "3.8"
services:
  readingbat0:
    image: "pambrose/readingbat:1.12.0"
    restart: "always"
    env_file: docker_env_vars
    ports:
      - "8080:8080"
      - "8083:8083"
      - "8084:8084"
  readingbat1:
    image: "pambrose/readingbat:1.12.0"
    restart: "always"
    env_file: docker_env_vars
    ports:
      - "8090:8080"
      - "8093:8083"
      - "8094:8084"
  readingbat2:
    image: "pambrose/readingbat:1.12.0"
    restart: "always"
    env_file: docker_env_vars
    ports:
      - "8070:8080"
      - "8073:8083"
      - "8074:8084"
