[versions]
# Plugins
kotlin = "2.2.0"
versions = "0.52.0"
buildconfig = "5.6.7"
shadow = "8.1.1"

# Dependencies
logging = "7.0.7"
readingbat = "2.1.0"
utils = "2.3.11"

[libraries]
# Dependencies
readingbat-core = { group = "com.github.readingbat", name = "readingbat-core", version.ref = "readingbat" }
core-utils = { group = "com.github.pambrose.common-utils", name = "core-utils", version.ref = "utils" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "logging" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }