[versions]
# Plugins
kotlin = "2.2.0"
versions = "0.52.0"
buildconfig = "5.6.7"

# Dependencies
logging = "7.0.12"
readingbat = "2.1.2"
ktor = "3.2.3"

[libraries]
# Dependencies
readingbat-core = { module = "com.github.readingbat.readingbat-core:readingbat-core", version.ref = "readingbat" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "logging" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }
